<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteById($id)
    {
        $query = $this->createQueryBuilder('u')
            ->delete()
            ->where('u.id = :id')
            ->setParameter(':id', $id);

        return $query->getQuery()->getResult();
    }
}
