app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_users:
    path:     /users
    defaults: { _controller: AppBundle:Default:users }

app_userSingle:
    path:     /user/{id}
    defaults: { _controller: AppBundle:Default:userSingle }

app_userDelete:
    path:     /user-delete/{id}
    defaults: { _controller: AppBundle:Default:userDelete }
    methods : [DELETE]

app_userCreate:
    path:     /user-create
    defaults: { _controller: AppBundle:Default:userCreate }
    methods : [GET, POST]
